# Generated by Django 5.2.1 on 2025-11-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bst', '0003_initial'),
        ('nser', '0001_initial'),
        ('operators', '0001_initial'),
        ('screening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusionauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusion_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusionextensionrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusionextensionrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusionextensionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exclusionextensionrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorexclusionmapping',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_mappings', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='bst_token',
            field=models.ForeignKey(help_text='Bematore Screening Token for cross-operator tracking', on_delete=django.db.models.deletion.PROTECT, related_name='exclusions', to='bst.bsttoken'),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='early_termination_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusion_terminations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='triggering_assessment',
            field=models.ForeignKey(blank=True, help_text='Assessment that triggered this exclusion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_exclusions', to='screening.assessmentsession'),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selfexclusionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatorexclusionmapping',
            name='exclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_mappings', to='nser.selfexclusionrecord'),
        ),
        migrations.AddField(
            model_name='exclusionextensionrequest',
            name='exclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='nser.selfexclusionrecord'),
        ),
        migrations.AddField(
            model_name='exclusionauditlog',
            name='exclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='nser.selfexclusionrecord'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['user', 'is_active'], name='excl_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['bst_token', 'is_active'], name='excl_bst_active_idx'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['exclusion_reference'], name='excl_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['status', 'effective_date'], name='excl_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['expiry_date', 'is_active'], name='excl_expiry_active_idx'),
        ),
        migrations.AddIndex(
            model_name='selfexclusionrecord',
            index=models.Index(fields=['is_active', 'effective_date', 'expiry_date'], name='excl_active_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='selfexclusionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', models.F('effective_date'))), name='excl_expiry_after_effective'),
        ),
        migrations.AddIndex(
            model_name='operatorexclusionmapping',
            index=models.Index(fields=['exclusion', 'operator'], name='opr_excl_map_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorexclusionmapping',
            index=models.Index(fields=['propagation_status', 'notified_at'], name='opr_excl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorexclusionmapping',
            index=models.Index(fields=['is_compliant'], name='opr_excl_comply_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorexclusionmapping',
            unique_together={('exclusion', 'operator')},
        ),
        migrations.AddIndex(
            model_name='exclusionauditlog',
            index=models.Index(fields=['exclusion', 'action'], name='excl_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusionauditlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='excl_audit_user_idx'),
        ),
        migrations.AddIndex(
            model_name='exclusionauditlog',
            index=models.Index(fields=['created_at'], name='excl_audit_time_idx'),
        ),
    ]
