# Generated by Django 5.2.1 on 2025-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_exclusions', models.PositiveIntegerField(default=0)),
                ('new_exclusions', models.PositiveIntegerField(default=0)),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('high_risk_users', models.PositiveIntegerField(default=0)),
                ('api_calls_total', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'analytics_daily_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OperatorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('date', models.DateField(db_index=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('screenings_conducted', models.PositiveIntegerField(default=0)),
                ('exclusions_enforced', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
            ],
            options={
                'db_table': 'analytics_operator_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(db_index=True, max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file_url', models.URLField(blank=True)),
                ('report_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
