# Generated by Django 5.2.1 on 2025-11-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorstatistics',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.operator'),
        ),
    ]
