# Generated by Django 5.2.1 on 2025-11-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_initial"),
        ("operators", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealTimeMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("active_sessions", models.PositiveIntegerField(default=0)),
                ("api_calls_per_minute", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0)),
                ("cpu_usage_percent", models.FloatField(default=0)),
                ("memory_usage_percent", models.FloatField(default=0)),
                ("database_connections", models.PositiveIntegerField(default=0)),
                ("queue_size", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_realtime_metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="dailystatistics",
            name="revenue_ksh",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="dailystatistics",
            name="transactions_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="operatorstatistics",
            name="avg_response_time_ms",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="operatorstatistics",
            name="revenue_ksh",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="GeographicAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("county", models.CharField(max_length=100)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_exclusions", models.PositiveIntegerField(default=0)),
                ("high_risk_users", models.PositiveIntegerField(default=0)),
                ("operator_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_geographic",
                "unique_together": {("date", "county")},
            },
        ),
        migrations.CreateModel(
            name="RiskAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("avg_score", models.FloatField(default=0)),
            ],
            options={
                "db_table": "analytics_risk_analytics",
                "unique_together": {("date", "risk_level")},
            },
        ),
        migrations.CreateModel(
            name="UserDemographics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("18-25", "18-25"),
                            ("26-35", "26-35"),
                            ("36-45", "36-45"),
                            ("46-55", "46-55"),
                            ("56+", "56+"),
                        ],
                        max_length=20,
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("user_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_user_demographics",
                "unique_together": {("date", "age_group", "county", "gender")},
            },
        ),
        migrations.CreateModel(
            name="APIUsageMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("date", models.DateField(db_index=True)),
                ("hour", models.PositiveSmallIntegerField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operators.operator",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_api_usage",
                "unique_together": {("operator", "endpoint", "date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("exclusion_checks_performed", models.PositiveIntegerField(default=0)),
                ("exclusion_checks_missed", models.PositiveIntegerField(default=0)),
                ("response_time_compliance", models.FloatField(default=100)),
                ("data_accuracy_score", models.FloatField(default=100)),
                ("audit_score", models.FloatField(default=100)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operators.operator",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_compliance_metrics",
                "unique_together": {("operator", "date")},
            },
        ),
    ]
