# Generated by Django 5.2.1 on 2025-11-05 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('widget_type', models.CharField(choices=[('exclusion_stats', 'Exclusion Statistics'), ('risk_distribution', 'Risk Distribution'), ('operator_compliance', 'Operator Compliance'), ('api_performance', 'API Performance'), ('recent_activities', 'Recent Activities')], max_length=50)),
                ('position_x', models.PositiveSmallIntegerField(default=0)),
                ('position_y', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=4)),
                ('height', models.PositiveSmallIntegerField(default=4)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboards_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
