# Generated by Django 5.2.1 on 2025-11-05 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc')], default='KES', max_length=3)),
                ('line_items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settlements_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc')], default='KES', max_length=3)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'settlements_ledger_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='MPesaIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('mpesa_receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settlements_mpesa_integration',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('reconciliation_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('variance', 'Variance Detected'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'settlements_reconciliations',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('transaction_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('screening_fee', 'Screening Fee'), ('license_fee', 'License Fee'), ('monthly_subscription', 'Monthly Subscription'), ('penalty', 'Penalty'), ('refund', 'Refund')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc')], default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('wallet', 'Digital Wallet')], max_length=50)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'settlements_transactions',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
