# Generated by Django 5.2.1 on 2025-11-05 07:11

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('question_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('assessment_type', models.CharField(choices=[('liebet', 'Lie/Bet (2-Question Screen)'), ('pgsi', 'PGSI (Problem Gambling Severity Index)'), ('dsm5', 'DSM-5 (Diagnostic and Statistical Manual)'), ('behavioral', 'Behavioral Pattern Analysis'), ('custom', 'Custom Assessment')], db_index=True, max_length=20)),
                ('question_number', models.PositiveSmallIntegerField(db_index=True)),
                ('question_text_en', models.TextField()),
                ('question_text_sw', models.TextField(blank=True)),
                ('response_type', models.CharField(default='yes_no', max_length=20)),
                ('response_options', models.JSONField(blank=True, default=dict)),
                ('max_score', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'screening_assessment_questions',
                'ordering': ['assessment_type', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('response_value', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'screening_assessment_responses',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('session_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('assessment_type', models.CharField(choices=[('liebet', 'Lie/Bet (2-Question Screen)'), ('pgsi', 'PGSI (Problem Gambling Severity Index)'), ('dsm5', 'DSM-5 (Diagnostic and Statistical Manual)'), ('behavioral', 'Behavioral Pattern Analysis'), ('custom', 'Custom Assessment')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='in_progress', max_length=20)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('none', 'No Risk'), ('low', 'Low Risk'), ('mild', 'Mild Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('severe', 'Severe Risk'), ('critical', 'Critical Risk'), ('blacklisted', 'Blacklisted')], db_index=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('am', 'Amharic'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('zu', 'Zulu'), ('af', 'Afrikaans'), ('pcm', 'Nigerian Pidgin')], default='en', max_length=10)),
                ('should_self_exclude', models.BooleanField(default=False)),
                ('next_assessment_due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ml_risk_prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'screening_assessment_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('total_bets_count', models.PositiveIntegerField(default=0)),
                ('total_amount_wagered', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('betting_frequency_daily', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_night_betting_count', models.PositiveIntegerField(default=0)),
                ('loss_chasing_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('anomaly_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'screening_behavioral_profiles',
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('score_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('risk_level', models.CharField(choices=[('none', 'No Risk'), ('low', 'Low Risk'), ('mild', 'Mild Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('severe', 'Severe Risk'), ('critical', 'Critical Risk'), ('blacklisted', 'Blacklisted')], db_index=True, max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_source', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'screening_risk_scores',
                'ordering': ['-score_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('schedule_type', models.CharField(db_index=True, max_length=20)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('is_compliant', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'screening_schedules',
                'ordering': ['due_date'],
            },
        ),
    ]
