"""
Analytics Admin Interface
Super Admin features for analytics data, reports, and insights
"""
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.utils.html import format_html
from .models import AnalyticsEvent, AnalyticsReport, UserSegment, Cohort


@admin.register(AnalyticsEvent)
class AnalyticsEventAdmin(admin.ModelAdmin):
    """Analytics event tracking"""
    list_display = (
        'event_name', 'event_type_badge', 'user_phone', 'event_date'
    )
    list_filter = ('event_type', 'event_name', 'event_date')
    search_fields = ('event_name', 'user__phone_number')
    readonly_fields = ('event_date', 'event_summary')
    
    fieldsets = (
        (_('Event'), {
            'fields': ('event_name', 'event_type')
        }),
        (_('User'), {
            'fields': ('user', 'session_id')
        }),
        (_('Data'), {
            'fields': ('event_data', 'properties'),
            'classes': ('collapse',)
        }),
        (_('Summary'), {
            'fields': ('event_summary',),
            'classes': ('collapse',)
        }),
    )
    
    def user_phone(self, obj):
        return obj.user.phone_number if obj.user else 'Anonymous'
    user_phone.short_description = _('User')
    
    def event_type_badge(self, obj):
        colors = {
            'page_view': '#2166ac',
            'click': '#7fbc41',
            'form_submit': '#b35806',
            'error': '#d73026',
            'custom': '#fc8d59'
        }
        color = colors.get(obj.event_type, '#cccccc')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 10px; border-radius: 3px;">{}</span>',
            color, obj.get_event_type_display()
        )
    event_type_badge.short_description = _('Type')
    
    def event_summary(self, obj):
        return format_html(
            '<div>'
            '<p><strong>Event:</strong> {}</p>'
            '<p><strong>Type:</strong> {}</p>'
            '<p><strong>User:</strong> {}</p>'
            '<p><strong>Date:</strong> {}</p>'
            '</div>',
            obj.event_name,
            obj.get_event_type_display(),
            obj.user.phone_number if obj.user else 'Anonymous',
            obj.event_date
        )
    event_summary.short_description = _('Summary')
    
    def has_add_permission(self, request):
        """Events are auto-generated by tracking system"""
        return False
    
    def has_delete_permission(self, request, obj=None):
        """Keep events for historical analysis"""
        return False


@admin.register(AnalyticsReport)
class AnalyticsReportAdmin(admin.ModelAdmin):
    """Analytics reports and insights"""
    list_display = (
        'report_name', 'report_type_badge', 'period_display', 'updated_at'
    )
    list_filter = ('report_type', 'updated_at')
    search_fields = ('report_name', 'description')
    readonly_fields = ('created_at', 'updated_at', 'report_summary')
    
    fieldsets = (
        (_('Report'), {
            'fields': ('report_name', 'report_type', 'description')
        }),
        (_('Period'), {
            'fields': ('period_start', 'period_end')
        }),
        (_('Content'), {
            'fields': ('metrics', 'insights', 'recommendations'),
            'classes': ('collapse',)
        }),
        (_('Summary'), {
            'fields': ('report_summary',),
            'classes': ('collapse',)
        }),
    )
    
    def report_type_badge(self, obj):
        colors = {
            'user_behavior': '#2166ac',
            'operator_performance': '#7fbc41',
            'compliance': '#b35806',
            'financial': '#d73026'
        }
        color = colors.get(obj.report_type, '#cccccc')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 10px; border-radius: 3px;">{}</span>',
            color, obj.get_report_type_display()
        )
    report_type_badge.short_description = _('Type')
    
    def period_display(self, obj):
        return f"{obj.period_start.strftime('%Y-%m-%d')} to {obj.period_end.strftime('%Y-%m-%d')}"
    period_display.short_description = _('Period')
    
    def report_summary(self, obj):
        return format_html(
            '<div>'
            '<p><strong>Report:</strong> {}</p>'
            '<p><strong>Type:</strong> {}</p>'
            '<p><strong>Period:</strong> {} to {}</p>'
            '</div>',
            obj.report_name,
            obj.get_report_type_display(),
            obj.period_start.strftime('%Y-%m-%d'),
            obj.period_end.strftime('%Y-%m-%d')
        )
    report_summary.short_description = _('Summary')
    
    def has_add_permission(self, request):
        """Reports are auto-generated"""
        return False


@admin.register(UserSegment)
class UserSegmentAdmin(admin.ModelAdmin):
    """User segmentation and cohort analysis"""
    list_display = ('segment_name', 'segment_type', 'user_count', 'updated_at')
    list_filter = ('segment_type', 'updated_at')
    search_fields = ('segment_name', 'description')
    readonly_fields = ('created_at', 'updated_at')
    
    fieldsets = (
        (_('Segment'), {
            'fields': ('segment_name', 'segment_type', 'description')
        }),
        (_('Criteria'), {
            'fields': ('criteria', 'filters'),
            'classes': ('collapse',)
        }),
    )
    
    def user_count(self, obj):
        return obj.users.count()
    user_count.short_description = _('Users')


@admin.register(Cohort)
class CohortAdmin(admin.ModelAdmin):
    """User cohort tracking"""
    list_display = ('cohort_name', 'cohort_start_date', 'user_count', 'updated_at')
    list_filter = ('cohort_start_date', 'updated_at')
    search_fields = ('cohort_name',)
    readonly_fields = ('created_at', 'updated_at')
    
    fieldsets = (
        (_('Cohort'), {
            'fields': ('cohort_name', 'cohort_start_date')
        }),
        (_('Criteria'), {
            'fields': ('acquisition_channel', 'initial_behavior'),
            'classes': ('collapse',)
        }),
    )
    
    def user_count(self, obj):
        return obj.users.count()
    user_count.short_description = _('Users')
