"""
Analytics Admin Interface
Super Admin features for analytics data, reports, and insights
"""
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.utils.html import format_html
from .models import (
    DailyStatistics, OperatorStatistics, RealTimeMetrics,
    UserDemographics, RiskAnalytics, ComplianceMetrics,
    GeographicAnalytics, APIUsageMetrics, Report
)


@admin.register(DailyStatistics)
class DailyStatisticsAdmin(admin.ModelAdmin):
    """Daily aggregated statistics"""
    list_display = ('date', 'total_users', 'active_exclusions', 'api_calls_total', 'revenue_ksh')
    list_filter = ('date',)
    search_fields = ('date',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False
    
    def has_delete_permission(self, request, obj=None):
        return False


@admin.register(OperatorStatistics)
class OperatorStatisticsAdmin(admin.ModelAdmin):
    """Per-operator statistics"""
    list_display = ('operator', 'date', 'screenings_conducted', 'exclusions_enforced', 'compliance_score')
    list_filter = ('operator', 'date')
    search_fields = ('operator__name',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(RealTimeMetrics)
class RealTimeMetricsAdmin(admin.ModelAdmin):
    """Real-time system metrics"""
    list_display = ('timestamp', 'active_sessions', 'api_calls_per_minute', 'cpu_usage_percent', 'memory_usage_percent')
    list_filter = ('timestamp',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(UserDemographics)
class UserDemographicsAdmin(admin.ModelAdmin):
    """User demographics data"""
    list_display = ('date', 'age_group', 'county', 'gender', 'user_count')
    list_filter = ('date', 'age_group', 'gender', 'county')
    search_fields = ('county',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(RiskAnalytics)
class RiskAnalyticsAdmin(admin.ModelAdmin):
    """Risk assessment analytics"""
    list_display = ('date', 'risk_level', 'user_count', 'avg_score')
    list_filter = ('date', 'risk_level')
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(ComplianceMetrics)
class ComplianceMetricsAdmin(admin.ModelAdmin):
    """Compliance tracking metrics"""
    list_display = ('operator', 'date', 'exclusion_checks_performed', 'response_time_compliance')
    list_filter = ('operator', 'date')
    search_fields = ('operator__name',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(GeographicAnalytics)
class GeographicAnalyticsAdmin(admin.ModelAdmin):
    """Geographic distribution analytics"""
    list_display = ('date', 'county', 'total_users', 'active_exclusions', 'operator_count')
    list_filter = ('date', 'county')
    search_fields = ('county',)
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(APIUsageMetrics)
class APIUsageMetricsAdmin(admin.ModelAdmin):
    """API usage tracking"""
    list_display = ('operator', 'endpoint', 'date', 'hour', 'request_count', 'error_count')
    list_filter = ('operator', 'date', 'endpoint')
    search_fields = ('operator__name', 'endpoint')
    readonly_fields = ('created_at', 'updated_at')
    
    def has_add_permission(self, request):
        return False


@admin.register(Report)
class ReportAdmin(admin.ModelAdmin):
    """Generated reports"""
    list_display = ('report_name', 'report_type', 'period_display', 'generated_by', 'created_at')
    list_filter = ('report_type', 'created_at')
    search_fields = ('report_name', 'report_type')
    readonly_fields = ('created_at', 'updated_at')
    
    fieldsets = (
        (_('Report'), {
            'fields': ('report_name', 'report_type')
        }),
        (_('Period'), {
            'fields': ('period_start', 'period_end')
        }),
        (_('Generated By'), {
            'fields': ('generated_by',)
        }),
        (_('Data'), {
            'fields': ('file_url', 'report_data'),
            'classes': ('collapse',)
        }),
    )
    
    def period_display(self, obj):
        return f"{obj.period_start.strftime('%Y-%m-%d')} to {obj.period_end.strftime('%Y-%m-%d')}"
    period_display.short_description = _('Period')
