# Generated by Django 5.2.1 on 2025-11-05 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField(help_text='One per line')),
                ('allowed_scopes', models.TextField(help_text='Space separated')),
                ('is_confidential', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'auth_oauth_applications',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('device_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'auth_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('method', models.CharField(choices=[('totp', 'TOTP App'), ('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('secret', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'auth_two_factor',
            },
        ),
    ]
