# Generated by Django 5.2.1 on 2025-11-05 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSTAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('generated', 'Token Generated'), ('validated', 'Token Validated'), ('used', 'Token Used'), ('rotated', 'Token Rotated'), ('compromised', 'Token Compromised'), ('deactivated', 'Token Deactivated'), ('lookup', 'Token Lookup'), ('cross_referenced', 'Cross Referenced')], db_index=True, max_length=50, verbose_name='action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('success', models.BooleanField(db_index=True, default=True, verbose_name='success')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
            ],
            options={
                'verbose_name': 'BST Audit Log',
                'verbose_name_plural': 'BST Audit Logs',
                'db_table': 'bst_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTCrossReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('identifier_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email Address'), ('national_id', 'National ID'), ('device_id', 'Device ID'), ('ip_address', 'IP Address'), ('sim_card', 'SIM Card Serial'), ('biometric', 'Biometric Hash')], db_index=True, max_length=50, verbose_name='identifier type')),
                ('identifier_hash', models.CharField(db_index=True, help_text='SHA-256 hash of identifier', max_length=64, verbose_name='identifier hash')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, verbose_name='first detected at')),
                ('detection_source', models.CharField(choices=[('registration', 'User Registration'), ('verification', 'ID Verification'), ('device_fingerprint', 'Device Fingerprinting'), ('behavioral', 'Behavioral Analysis'), ('operator_report', 'Operator Report')], max_length=50, verbose_name='detection source')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Confidence that this identifier belongs to user (0-100)', max_digits=5, verbose_name='confidence score')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this cross-reference is verified', verbose_name='is verified')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'BST Cross Reference',
                'verbose_name_plural': 'BST Cross References',
                'db_table': 'bst_cross_references',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('operator_user_id', models.CharField(help_text="User ID in operator's system", max_length=255, verbose_name='operator user ID')),
                ('operator_username', models.CharField(blank=True, max_length=255, verbose_name='operator username')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='first seen at')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='last seen at')),
                ('interaction_count', models.PositiveIntegerField(default=0, verbose_name='interaction count')),
                ('last_activity_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('login', 'Login'), ('deposit', 'Deposit'), ('bet', 'Bet Placed'), ('withdrawal', 'Withdrawal'), ('lookup', 'Status Lookup')], max_length=50, verbose_name='last activity type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('is_primary_operator', models.BooleanField(default=False, help_text='First operator user registered with', verbose_name='is primary operator')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'BST Mapping',
                'verbose_name_plural': 'BST Mappings',
                'db_table': 'bst_mappings',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='date')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='total tokens')),
                ('active_tokens', models.PositiveIntegerField(default=0, verbose_name='active tokens')),
                ('new_tokens_today', models.PositiveIntegerField(default=0, verbose_name='new tokens today')),
                ('rotated_tokens_today', models.PositiveIntegerField(default=0, verbose_name='rotated today')),
                ('compromised_tokens_today', models.PositiveIntegerField(default=0, verbose_name='compromised today')),
                ('total_lookups_today', models.PositiveIntegerField(default=0, verbose_name='total lookups today')),
                ('avg_lookup_time_ms', models.FloatField(default=0.0, verbose_name='avg lookup time (ms)')),
                ('max_lookup_time_ms', models.FloatField(default=0.0, verbose_name='max lookup time (ms)')),
                ('duplicate_accounts_detected', models.PositiveIntegerField(default=0, verbose_name='duplicates detected')),
                ('fraud_attempts_blocked', models.PositiveIntegerField(default=0, verbose_name='fraud attempts blocked')),
                ('operators_active', models.PositiveIntegerField(default=0, verbose_name='operators active')),
                ('cross_operator_users', models.PositiveIntegerField(default=0, verbose_name='cross-operator users')),
            ],
            options={
                'verbose_name': 'BST Statistics',
                'verbose_name_plural': 'BST Statistics',
                'db_table': 'bst_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BSTToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - data never actually deleted', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True, verbose_name='deleted at')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for soft deletion', verbose_name='deletion reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who created/updated', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='user agent')),
                ('encryption_key_id', models.CharField(blank=True, db_index=True, help_text='ID of the encryption key used (for key rotation)', max_length=64, null=True, verbose_name='encryption key ID')),
                ('encrypted_at', models.DateTimeField(blank=True, help_text='Timestamp when data was encrypted', null=True, verbose_name='encrypted at')),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', help_text='Encryption algorithm used', max_length=50, verbose_name='encryption algorithm')),
                ('token', models.CharField(db_index=True, help_text='Full BST token string', max_length=100, unique=True, verbose_name='BST token')),
                ('token_version', models.CharField(db_index=True, default='02', help_text='Token format version for future upgrades', max_length=10, verbose_name='token version')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-512 hash part of token', max_length=64, unique=True, verbose_name='token hash')),
                ('token_checksum', models.CharField(help_text='Luhn checksum for validation', max_length=10, verbose_name='token checksum')),
                ('phone_number_hash', models.CharField(db_index=True, help_text='SHA-256 hash of phone number', max_length=64, verbose_name='phone number hash')),
                ('national_id_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of national ID', max_length=64, null=True, verbose_name='national ID hash')),
                ('biometric_hash', models.CharField(blank=True, help_text='Hash of biometric data (if available)', max_length=64, null=True, verbose_name='biometric hash')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='issued at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiry (usually never expires)', null=True, verbose_name='expires at')),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last used at')),
                ('salt', models.CharField(help_text='Cryptographic salt used in generation', max_length=64, verbose_name='salt')),
                ('is_compromised', models.BooleanField(db_index=True, default=False, help_text='Flag if token security is compromised', verbose_name='is compromised')),
                ('compromised_at', models.DateTimeField(blank=True, null=True, verbose_name='compromised at')),
                ('compromised_reason', models.TextField(blank=True, verbose_name='compromised reason')),
                ('rotation_count', models.PositiveIntegerField(default=0, help_text='Number of times token has been rotated', verbose_name='rotation count')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='rotated at')),
                ('lookup_count', models.PositiveIntegerField(default=0, help_text='Number of times token was looked up', verbose_name='lookup count')),
                ('operator_count', models.PositiveIntegerField(default=0, help_text='Number of operators that have used this token', verbose_name='operator count')),
                ('generation_metadata', models.JSONField(blank=True, default=dict, help_text='Technical details of token generation', verbose_name='generation metadata')),
            ],
            options={
                'verbose_name': 'BST Token',
                'verbose_name_plural': 'BST Tokens',
                'db_table': 'bst_tokens',
                'ordering': ['-issued_at'],
            },
        ),
    ]
