# Generated by Django 5.2.1 on 2025-11-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bst', '0002_initial'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bstauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bstmapping',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bstmapping',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bstmapping',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bst_mappings', to='operators.operator'),
        ),
        migrations.AddField(
            model_name='bstmapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsttoken',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsttoken',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsttoken',
            name='previous_token',
            field=models.ForeignKey(blank=True, help_text='Previous token if rotated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tokens', to='bst.bsttoken'),
        ),
        migrations.AddField(
            model_name='bsttoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bsttoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bstmapping',
            name='bst_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='bst.bsttoken'),
        ),
        migrations.AddField(
            model_name='bstcrossreference',
            name='bst_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='bst.bsttoken'),
        ),
        migrations.AddField(
            model_name='bstauditlog',
            name='bst_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='bst.bsttoken'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['token'], name='bst_token_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['user', 'is_active'], name='bst_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['phone_number_hash'], name='bst_phone_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['national_id_hash'], name='bst_id_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['is_compromised', 'is_active'], name='bst_security_idx'),
        ),
        migrations.AddIndex(
            model_name='bsttoken',
            index=models.Index(fields=['last_used_at'], name='bst_last_used_idx'),
        ),
        migrations.AddIndex(
            model_name='bstmapping',
            index=models.Index(fields=['bst_token', 'operator'], name='bst_map_token_op_idx'),
        ),
        migrations.AddIndex(
            model_name='bstmapping',
            index=models.Index(fields=['operator', 'operator_user_id'], name='bst_map_op_user_idx'),
        ),
        migrations.AddIndex(
            model_name='bstmapping',
            index=models.Index(fields=['is_primary_operator'], name='bst_map_primary_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bstmapping',
            unique_together={('bst_token', 'operator')},
        ),
        migrations.AddIndex(
            model_name='bstcrossreference',
            index=models.Index(fields=['bst_token', 'identifier_type'], name='bst_xref_token_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bstcrossreference',
            index=models.Index(fields=['identifier_hash'], name='bst_xref_hash_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bstcrossreference',
            unique_together={('identifier_type', 'identifier_hash')},
        ),
        migrations.AddIndex(
            model_name='bstauditlog',
            index=models.Index(fields=['bst_token', 'action'], name='bst_audit_token_action_idx'),
        ),
        migrations.AddIndex(
            model_name='bstauditlog',
            index=models.Index(fields=['operator', 'created_at'], name='bst_audit_op_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bstauditlog',
            index=models.Index(fields=['created_at'], name='bst_audit_time_idx'),
        ),
    ]
